# Generated by Django 5.0.1 on 2024-04-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='id',
            new_name='RoomID',
        ),
    ]
