# Generated by Django 5.0.1 on 2024-04-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_records',
            name='DateTime',
            field=models.CharField(max_length=155),
        ),
    ]
