# Generated by Django 5.0.1 on 2024-04-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('BuildingID', models.AutoField(primary_key=True, serialize=False)),
                ('Building_Name', models.CharField(max_length=150)),
                ('Year_Built', models.DateField(max_length=15)),
                ('Number_people', models.DateField(max_length=15)),
            ],
        ),
    ]
