# Generated by Django 5.0.1 on 2024-04-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='Year_Built',
            field=models.CharField(max_length=150),
        ),
    ]
