# Generated by Django 5.0.1 on 2024-04-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_building_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='Number_people',
            field=models.IntegerField(),
        ),
    ]
