# Generated by Django 5.0.2 on 2024-04-12 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_permissions', '0001_initial'),
        ('persons', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_permission',
            name='RoomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='access_permission',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
    ]
