# Generated by Django 5.0.1 on 2024-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_permissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_permission',
            name='Building_Hours',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='access_permission',
            name='Room_Hours',
            field=models.CharField(max_length=155),
        ),
    ]
